name: Docker Image CI

on:
  push:
    branches: ["wulu"]
  pull_request:
    branches: ["wulu"]
    types: [closed]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: nxthongbk
          password: dckr_pat_kaeMIdxFIF0NVPS6vx82yGZo69k

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: nxthongbk/scity-ui-service:wulu

  Deploy:
    if: |
      (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) ||
      (github.event_name == 'push' && github.ref == 'refs/heads/wulu')
    needs: Build
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Build & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/nxthong/Desktop/scity && sudo docker-compose pull scity-ui && sudo docker-compose up -d scity-ui
